### ISSUE TITLE
Clarify docker instructions

### ISSUE THREAD

**Issue by sphen13** [devDomotz/domotzpro-agent-docker#2]
I have been running the agent via docker with success, thank you very much. I wanted to know if we could get some clarity on a few things or modify the readme.

you mention that you can set the mac-address to ensure that the agent stays registered within domotz properly. however, the options `--network=host` and `--mac-address="XX:XX:XX:XX:XX:XX"` are not compatible with each other. host networking forces the mac so this instruction is not valid. is there a recommended way to run without host networking? i would assume if so we would lose other functionality / multiple vlan etc so would not be good.

alternatively you mention that we could pass `/opt/domotz/etc` as a volume (or at least how i read it), but if i do that the container errors out as there are other files within that location that the container depends on. is there something more specific that we should pass as a volume that doesnt conflict with other required files?

thank you!

**Comment by MartynKeigher** [comment]
Hey @sphen13 

I too was a bit confused by this, but in the interest of 'sharing is caring', here is the docker-compose.yml I am using for my project. 

```
version: "3"
services:
  domotz:
    image: domotz/domotzpro-agent-amd64:latest
    container_name: domotz
    restart: always
    mac_address: 02:42:ac:d0:d1:d2
    ports:
      - 8080:3000
    cap_add:
      - NET_ADMIN
    networks:
      - domotz
    volumes:
      - vol-domotz:/opt/domotz/etc

networks:
  domotz:
    external: false

volumes:
  vol-domotz:
    external: false
```

then, do `docker-compose up -d --build` to get it going! 

The container starts up without issues and it maintains everything after restarts, etc...

I used the mac addresses of pre-existing containers on the same docker host as a reference to provide the docker-compose with something unique.

After initial startup, I then add my docker HOST network (& others)) as a 'Private subnet' in the Domoz UI and things just start falling into place! :) 

i.e: 
container network: 172.30.0.0/24 _(default network on container startup)_
docker host (aka: my server) network: 192.168.10.0/24
wireless network: 192.168.50.0/24
IoT network: 10.10.10.0/24

Hope this helps. :) 

PS: I had to change the ports as I am running Grafana already, and it's configured to use port 3000:3000
